=== retra/retra-system/app-retra/src/main/webapp/WEB-INF/lovs/lovs.dtd
<!ELEMENT lovs (lov)*>

<!ELEMENT lov (field)*>
<!ATTLIST lov
              code CDATA #REQUIRED
              description CDATA #IMPLIED
>

<!ELEMENT field EMPTY>
<!ATTLIST field
              value CDATA #REQUIRED
              key CDATA #REQUIRED
>

=== retra/retra-system/src/main/webapp/WEB-INF/lovs/years.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lovs SYSTEM "lovs.dtd">

<lovs>
	<lov code="years" description="All years">
		<field value="2000" key="year.2000" />
		<field value="2001" key="year.2001" />
		<field value="2002" key="year.2002" />
		<field value="2003" key="year.2003" />
		<field value="2004" key="year.2004" />
		<field value="2005" key="year.2005" />
		<field value="2006" key="year.2006" />
		<field value="2007" key="year.2007" />
		<field value="2008" key="year.2008" />
		<field value="2009" key="year.2009" />
		<field value="2010" key="year.2010" />
		<field value="2011" key="year.2011" />
		<field value="2012" key="year.2012" />
		<field value="2013" key="year.2013" />
		<field value="2014" key="year.2014" />
		<field value="2015" key="year.2015" />
		<field value="2016" key="year.2016" />
		<field value="2017" key="year.2017" />
		<field value="2018" key="year.2018" />
		<field value="2019" key="year.2019" />
		<field value="2020" key="year.2020" />
		<field value="2021" key="year.2021" />
		<field value="2022" key="year.2022" />
		<field value="2023" key="year.2023" />
		<field value="2024" key="year.2024" />
		<field value="2025" key="year.2025" />
		<field value="2026" key="year.2026" />
		<field value="2027" key="year.2027" />
		<field value="2028" key="year.2028" />
		<field value="2029" key="year.2029" />
		<field value="2030" key="year.2030" />
		<field value="2030" key="year.2030" />
		<field value="2031" key="year.2031" />
		<field value="2032" key="year.2032" />
		<field value="2033" key="year.2033" />
		<field value="2034" key="year.2034" />
		<field value="2035" key="year.2035" />
		<field value="2036" key="year.2036" />
		<field value="2037" key="year.2037" />
		<field value="2038" key="year.2038" />
		<field value="2039" key="year.2039" />
		<field value="2040" key="year.2040" />
	</lov>
</lovs>

=== retra/retra-system/src/main/webapp/WEB-INF/lovs/months.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lovs SYSTEM "lovs.dtd">

<lovs>
	<lov code="months" description="All months">
		<field value="0" key="month.0" />
		<field value="1" key="month.1" />
		<field value="2" key="month.2" />
		<field value="3" key="month.3" />
		<field value="4" key="month.4" />
		<field value="5" key="month.5" />
		<field value="6" key="month.6" />
		<field value="7" key="month.7" />
		<field value="8" key="month.8" />
		<field value="9" key="month.9" />
		<field value="10" key="month.10" />
		<field value="11" key="month.11" />
	</lov>
</lovs>

=== retra/retra-system/app-retra/src/main/webapp/WEB-INF/lovs/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lovs SYSTEM "lovs.dtd">

<lovs>
	<lov code="scheduleStates" description="All schedule states">
		<field value="0" key="schedule.state.0" />
		<field value="1" key="schedule.state.1" />
		<field value="2" key="schedule.state.2" />
		<field value="3" key="schedule.state.3" />
		<field value="4" key="schedule.state.4" />
	</lov>
	<lov code="scheduleCopyTypes" description="All schedule types of copy">
		<field value="0" key="schedule.copyType.0" />
		<field value="1" key="schedule.copyType.1" />
	</lov>
</lovs>

=== retra/retra-system/app-retra/src/main/webapp/WEB-INF/lovs/days.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lovs SYSTEM "lovs.dtd">

<lovs>
	<lov code="days" description="All days">
		<field value="2" key="day.2" />
		<field value="3" key="day.3" />
		<field value="4" key="day.4" />
		<field value="5" key="day.5" />
		<field value="6" key="day.6" />
		<field value="7" key="day.7" />
		<field value="1" key="day.1" />
	</lov>
</lovs>
